4 TO - DO - Task


4.1 Exercise on Functions:

Task - 1:
Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:

      – Convert meters (m) to feet (ft).

      – Convert feet (ft) to meters (m).

2. Weight:

      – Convert kilograms (kg) to pounds (lbs).

      – Convert pounds (lbs) to kilograms (kg).

3. Volume:

      – Convert liters (L) to gallons (gal).

      – Convert gallons (gal) to liters (L).

In [ ]:
def conversion (a, choice):
  '''
  Convert a value between different units of measurement.

  Parameters:
  a (float): a float value
  choice (str): user input

  Returns:
  function returns the operation output.
  '''
  if (choice == "1"):
    meter_feet = a * 3.281
    feet_meter = a / 3.281

    return meter_feet, feet_meter

  elif (choice == "2"):
    kilo_pound = a * 2.2
    pound_kilo = a / 2.2

    return kilo_pound, pound_kilo

  elif (choice == "3"):
    liter_gallon = a * 0.264
    gallon_liter = a / 0.264

    return liter_gallon, gallon_liter




try:
    choice = input("Choose the type of conversion: \n"
                        "1. Length \n"
                        "2. Weight \n"
                        "3. Volume\n")
    value = float(input("Enter the number: "))

    if(choice == "1"):
      output1, output2 = conversion(value, choice)
      print(f"Meter -> Feet: {output1:.2f}, Feet -> Meter: {output2:.2f}")
    elif(choice == "2"):
      output1, output2 = conversion(value, choice)
      print(f"Kilogram -> Pound: {output1:.2f}, Pound -> Kilogram: {output2:.2f}")
    elif(choice == "3"):
      output1, output2 = conversion(value, choice)
      print(f"Liter -> Gallon: {output1:.2f}, Gallon -> Liter: {output2:.2f}")
    else:
      print("Invalid choice.")


except ValueError:
    print("Non-Numeric number is not excepted.")



Choose the type of conversion: 
1. Length 
2. Weight 
3. Volume
5
Enter the number: 5
Invalid choice.


Task - 2: Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def add(num):
  '''
  Sums the list number using iteration.

  Parameter:
  num[List]: list of userinput numbers.

  Returns:
  sum: operation output
  '''
  sum = 0
  for i in num:
    sum += i

  return sum

def average(output, num):
  '''
  Finds the average value of numbers in list

  Parameter:
  num[List]: list of userinput numbers.

  Returns:
  average: operation output
  '''
  average = output/len(num)

  return average


def maximum(num):
  '''
  Finds the maximum value from the list

  Parameter:
  num[List]: list of userinput numbers.

  Returns:
  max_num(float): maximum value
  '''
  max_num = num[0]
  for i in num:
    if i > max_num:
      max_num = i
  return max_num


def minimum(num):
  '''
  Finds the minumum value from the list

  Parameter:
  num[List]: list of userinput numbers.

  Returns:
  mini_num (float): minimum value
  '''
  mini_num = num[0]
  for i in num:
    if i < mini_num:
      mini_num = i

  return mini_num


try:
  choice = input("Choose an operation: \n"
                "1. Sum \n"
                "2. Average \n"
                "3. Maximum\n"
                "4. Minimum \n")
  user_input = input("Enter the list of numbers (separated by spaces)"). split()
  if not user_input:
        raise ValueError("Empty input! Please enter some numbers.")

  num = list(map(float, user_input))

  if (choice == "1"):
    output = add(num)
    print("Sum: ", output)

  elif (choice == "2"):
    output = add(num)
    output2 = average(output, num)
    print("Average: ", output2)

  elif (choice == "3"):
    output = maximum(num)
    print("Maximum: ", output)

  elif(choice == "4"):
    output = minimum(num)
    print("Minimum: ", output)

  else:
    print("Invalid Choice.")

except (ValueError, TypeError):
  print("Invalid Input.")


Choose an operation: 
1. Sum 
2. Average 
3. Maximum
4. Minimum 
1
Enter the list of numbers (separated by spaces)
Sum:  0


4.2 Exercise on List Manipulation:

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
  '''
  Extracts the everyother element from the original list starting from the first element.

  Parameter:
  lst(list) = list of userinput numbers

  Returns:
  new_list (list)= new list of every other elements from the original list
  '''
  new_lst = []
  for i in range(len(lst)):
    if i% 2 ==0:
      new_lst.append(lst[i])

  return new_lst



try:
  user = input("Enter the list of numbers: "). split()
  if not user:
        raise ValueError("Empty input! Please enter some numbers.")

  lst = list(map(int, user))
  output = extract_every_other(lst)
  print(output)

except (ValueError, TypeError) as e:
  print("Invalid input: ", e)

Enter the list of numbers: 1 2 3 4 5 
[1, 3, 5]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
  '''
  Returns a sublist from a given list starting from the specified start index
  and ending at the specified end index (inclusive).

  Parameters:
  lst (list): The original list from which to extract the sublist.
  start (int): The starting index of the sublist (inclusive).
  end (int): The ending index of the sublist (inclusive).

  Returns:
  sub_lst: A new list containing elements from index `start` to `end` of `lst`.
  '''

  sub_lst = []
  for i in range(start, end+1):
    sub_lst.append(lst[i])

  return sub_lst

try:
  user = input("Enter the list of numbers: "). split()
  if not user:
        raise ValueError("Empty input! Please enter some numbers.")
  lst = list(map(int, user))

  start = int(input("Enter the starting index: "))
  end = int(input("Enter the ending index: "))
  output = get_sublist(lst, start, end)
  print(output)

except (ValueError, IndexError) as e:
  print("Error: ", e)

Enter the list of numbers: 1 2 3 4 5 6
Enter the starting index: 
Error:  invalid literal for int() with base 10: ''


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """
    Returns a reversed version of the input list using slicing.

    Parameters:
    lst (list): The original list to be reversed.

    Returns:
    list: A new list containing the elements of lst in reverse order.
    """
    return lst[::-1]

user = input("Enter the list of numbers (with space)"). split()
if not user:
  raise ValueError("Empty input! Please enter some numbers.")


lst = list(map(int, user))
output = reverse_list(lst)
print(output)

Enter the list of numbers (with space)1 2 3 4 5
[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """
    Returns a new list with the first and last elements removed
    using slicing.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list containing all elements of lst
          except the first and last.
    """
    return lst[1:-1]


lst = [1,2, 3, 4, 5]
output = remove_first_last(lst)
print(output)

[2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
  '''
  Returns the first n number from the list using slicing

  Parameters:
  lst[list] : the oirginal list
  n (int): first n elements of the list

  Returns:
  list: list containg first n number of elements
  '''

  return lst[:n]

try:
  lst = [1, 2, 3, 4, 5]
  n = int(input("Enter the number to get first n elements: "))

  if not n:
    raise ValueError("Empty input! Please enter some number")
  output = get_first_n(lst, n)
  print(output)

except(ValueError) as e:
  print("Error: ", e)


Enter the number to get first n elements: 5
[1, 2, 3, 4, 5]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_first_n(lst, n):
  '''
  Returns the first n number from the list using slicing

  Parameters:
  lst[list] : the oirginal list
  n (int): first n elements of the list

  Returns:
  list: list containg first n number of elements
  '''
  return lst[-n:]

try:
  lst = [1, 2, 3, 4, 5]
  n = int(input("Enter the number to get first n elements: "))

  if not n:
    raise ValueError("Empty input! Please enter some number")
  output = get_first_n(lst, n)
  print(output)

except(ValueError) as e:
  print("Error: ", e)


Enter the number to get first n elements: 2
[4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    '''
    Returns a new list containing every second element of the input list,
    starting from the second-to-last element and moving backward.

    Parameters:
    lst (list): The original list from which elements are to be extracted.

    Returns:
    list: A new list containing every second element in reverse order,
          starting from the second-to-last element.
    '''
    reversed_lst = lst[::-1]
    new_lst = []
    for i in range(1, len(reversed_lst), 2):
        new_lst.append(reversed_lst[i])
    return new_lst


lst = [1, 2, 3, 4, 5, 6]
output = reverse_skip(lst)
print(output)

[5, 3, 1]


4.3 Exercise on Nested List:

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [6]:
def flatten(nested_lst):
  '''
    Flattens a 2D (nested) list into a single list.

    Parameters:
    nested_lst (list): A list containing other lists as elements.

    Returns:
    list: A single list containing all the elements from the nested lists.
  '''
  single_lst = []
  for i in range(len(nested_lst)):
    for j in range(len(nested_lst[i])):
      single_lst.append(nested_lst[i][j])

  return single_lst

nested_lst = [[1,2], [3,4],[5]]
output = flatten(nested_lst)
print(output)

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,2], the output should be 6.

In [6]:
def extract(lst, indices):
  '''
    Returns an element from a nested list using a list of indices.

    Parameters:
    lst (list): A nested list.
    indices (list): A list of indices that represent the position of the element.

    Returns:
    element: The element located at the specified indices.
  '''
  element = lst
  for i in indices:
    element = element[i]
  return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1,1]
output = extract(lst, indices)
print(output)

5


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [4]:
def sum_nested(lst):
  '''
  Calculate the sum of all numbers in a nested list.

  Parameters:
  lst (list): A list that may contain integers and nested lists.

  Returns:
  int: The total sum of all numbers in the nested list.
  '''

  total = 0
  for i in lst:
    if isinstance(i, list):
      total += sum_nested(i)
    else:
      total += i
  return total


lst = [[1, 2], [3, [4, 5]], 6]
output = sum_nested(lst)
print(output)

21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [5]:
def remove_element(lst, elem):
    '''
    Remove all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): A list that may contain nested lists.
    elem: The element to remove from the list.

    Returns:
    list: The modified list with all occurrences of elem removed.
    '''
    new_lst = []

    for i in lst:
        if isinstance(i, list):
            new_lst.append(remove_element(i, elem))
        else:
            if i != elem:
                new_lst.append(i)

    return new_lst


lst = [[1, 2], [3, 2], [4, 5]]
print(remove_element(lst, 2))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [7]:
def find_max(lst):
    '''
    Find the maximum element in a nested list.

    Parameters:
    lst (list): A list that may contain integers and nested lists.

    Returns:
    int: The maximum value in the nested list.
    '''

    max_val = None

    for i in lst:
        if isinstance(i, list):
            value = find_max(i)
        else:
            value = i

        if max_val is None or value > max_val:
            max_val = value

    return max_val


lst = [[1, 2], [3, [4, 5]], 6]
print(find_max(lst))

6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [8]:
def count_occurrences(lst, elem):
    '''
    Count how many times a specific element appears in a nested list.

    Parameters:
    lst (list): A list that may contain nested lists.
    elem: The element whose occurrences need to be counted.

    Returns:
    int: The total number of times elem appears in the nested list.

    '''

    count = 0

    for i in lst:
        if isinstance(i, list):
            count += count_occurrences(i, elem)
        else:
            if i == elem:
                count += 1

    return count


lst = [[1, 2], [2, 3], [2, 4]]
print(count_occurrences(lst, 2))

3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def flatten(lst):
    '''
    Flatten a deeply nested list into a single list.

    Parameters:
    lst (list): A list that may contain other lists at any depth.

    Returns:
    list: A single flattened list containing all elements.

    '''

    flat_list = []

    for i in lst:
        if isinstance(i, list):
            flat_list.extend(flatten(i))
        else:
            flat_list.append(i)

    return flat_list


lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(flatten(lst))

8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [9]:
def average_nested(lst):
    '''
    Calculate the average of all numbers in a nested list.

    Parameters:
    lst (list): A list that may contain integers and nested lists.

    Returns:
    float: The average of all numbers in the nested list.

    Example:
    >>> average_nested([[1, 2], [3, 4], [5, 6]])
    3.5
    '''

    total = 0
    count = 0

    for i in lst:
        if isinstance(i, list):
            sub_sum, sub_count = average_nested(i)
            total += sub_sum
            count += sub_count
        else:
            total += i
            count += 1

    return total, count


def calculate_average(lst):
    total, count = average_nested(lst)
    return total / count


lst = [[1, 2], [3, 4], [5, 6]]
print(calculate_average(lst))

3.5


10 To - Do - NumPy

10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [2]:
import numpy as np

In [1]:

# 1. Initialize an empty array with size 2x2
arr1 = np.empty((2, 2))
print("Empty array (2x2):")
print(arr1)

# 2. Initialize an all-one array with size 4x2
arr2 = np.ones((4, 2))
print("\nAll ones array (4x2):")
print(arr2)

# 3. Return a new array filled with a specific value using np.full()
arr3 = np.full((3, 3), 7)
print("\nArray filled with value 7:")
print(arr3)

# 4. Return a new array of zeros with same shape and type as arr2
arr4 = np.zeros_like(arr2)
print("\nZeros array with same shape as arr2:")
print(arr4)

# 5. Return a new array of ones with same shape and type as arr2
arr5 = np.ones_like(arr2)
print("\nOnes array with same shape as arr2:")
print(arr5)

# 6. Convert list to NumPy array
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print("\nNumPy array from list:")
print(arr6)

Empty array (2x2):
[[1.98184346e-315 0.00000000e+000]
 [1.01385647e-091 1.18600496e-259]]

All ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array with same shape as arr2:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones array with same shape as arr2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

NumPy array from list:
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [3]:


# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr1)

# 2. Create a 3x3 matrix with values from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix from 0 to 8:")
print(arr2)

# 3. Create a 3x3 identity matrix
arr3 = np.eye(3)
print("\n3. 3x3 Identity matrix:")
print(arr3)

# 4. Create a random array of size 30 and find the mean
arr4 = np.random.random(30)
print("\n4. Random array of size 30:")
print(arr4)
print("Mean:", arr4.mean())

# 5. Create a 10x10 array with random values and find min and max
arr5 = np.random.random((10, 10))
print("\n5. 10x10 random array:")
print(arr5)
print("Minimum:", arr5.min())
print("Maximum:", arr5.max())

# 6. Create a zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\n6. Zero array with 5th element replaced by 1:")
print(arr6)

# 7. Reverse an array
arr7 = np.array([1,2,0,0,4,0])
arr7 = arr7[::-1]
print("\n7. Reversed array:")
print(arr7)

# 8. Create a 2D array with 1 on border and 0 inside
arr8 = np.ones((5,5))
arr8[1:-1, 1:-1] = 0
print("\n8. 2D array with border 1 and inside 0:")
print(arr8)

# 9. Create an 8x8 checkerboard pattern
arr9 = np.zeros((8,8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:")
print(arr9)

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
[0.65199333 0.05509976 0.68859777 0.53204098 0.09176191 0.2751273
 0.4589633  0.84772663 0.48563621 0.91794035 0.43876439 0.44120085
 0.65858682 0.79236683 0.58387221 0.53503366 0.56443785 0.84758878
 0.90373384 0.2500167  0.54939348 0.09841707 0.65755863 0.73158933
 0.04172828 0.47988661 0.55289534 0.71497733 0.12599493 0.30621389]
Mean: 0.5093048122763297

5. 10x10 random array:
[[0.83489454 0.55681772 0.43891227 0.31406074 0.65284488 0.55279252
  0.03274541 0.23003254 0.73694467 0.50218898]
 [0.20788438 0.77079054 0.70762366 0.47226133 0.14877929 0.45431087
  0.63176487 0.35425536 0.60893774 0.14865175]
 [0.20361867 0.38434065 0.17040988 0.05239357 0.04071953 0.30863763
  0.19021099 0.09974776 

Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [4]:

# Given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add the two arrays
add_xy = x + y
print("1. Addition:")
print(add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\n2. Subtraction:")
print(sub_xy)

# 3. Multiply the array with an integer
mul_x = x * 3
print("\n3. Multiply x by 3:")
print(mul_x)

# 4. Square each element
square_x = x ** 2
print("\n4. Square of elements in x:")
print(square_x)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\n5. Dot Products:")
print("v . w =", dot_vw)
print("x . v =", dot_xv)
print("x . y =")
print(dot_xy)

# 6. Concatenate arrays
concat_xy_row = np.concatenate((x, y), axis=0)  # along rows
concat_vw_col = np.vstack((v, w))               # stack as rows (column style)

print("\n6. Concatenate x and y along rows:")
print(concat_xy_row)

print("\nConcatenate v and w along column style:")
print(concat_vw_col)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v))
    print("\nConcatenate x and v:")
    print(concat_xv)
except Exception as e:
    print("\n7. Error when concatenating x and v:")
    print(e)

1. Addition:
[[ 6  8]
 [10 13]]

2. Subtraction:
[[-4 -4]
 [-4 -3]]

3. Multiply x by 3:
[[ 3  6]
 [ 9 15]]

4. Square of elements in x:
[[ 1  4]
 [ 9 25]]

5. Dot Products:
v . w = 219
x . v = [29 77]
x . y =
[[19 22]
 [50 58]]

6. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along column style:
[[ 9 10]
 [11 12]]

7. Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [5]:

# Given matrices
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)

print("A inverse:")
print(A_inv)

print("\nA * A^-1 (Identity matrix):")
print(result)


# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:")
print(AB)

print("\nBA:")
print(BA)


# 3. Prove (AB)^T = B^T A^T
left = (AB).T
right = np.dot(B.T, A.T)

print("\n(AB)^T:")
print(left)

print("\nB^T A^T:")
print(right)

# Solve Linear Equations AX = B
# System:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

A_matrix = np.array([[2,-3,1],
                     [1,-1,2],
                     [3,1,-1]])

B_matrix = np.array([-1,-3,9])

# Inverse method
A_inv = np.linalg.inv(A_matrix)

X = np.dot(A_inv, B_matrix)

print("\nSolution of equations (x, y, z):")
print(X)

A inverse:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1 (Identity matrix):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

(AB)^T:
[[23 51]
 [13 29]]

B^T A^T:
[[23 51]
 [13 29]]

Solution of equations (x, y, z):
[ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [6]:

import time

# Create lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Using Python Lists
start = time.time()

result_list = [list1[i] + list2[i] for i in range(len(list1))]

end = time.time()

print("Time taken using Python lists:", end - start)


# Using NumPy Arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

result_array = arr1 + arr2

end = time.time()

print("Time taken using NumPy arrays:", end - start)

Time taken using Python lists: 0.0713191032409668
Time taken using NumPy arrays: 0.00235748291015625


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [7]:


# Create lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Using Python Lists

start = time.time()

result_list = [list1[i] * list2[i] for i in range(len(list1))]

end = time.time()

print("Time taken using Python lists:", end - start)

# Using NumPy Arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

result_array = arr1 * arr2

end = time.time()

print("Time taken using NumPy arrays:", end - start)

Time taken using Python lists: 0.11238956451416016
Time taken using NumPy arrays: 0.0024983882904052734


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [8]:
import numpy as np
import time

# Create lists of size 1,000,000
list1 = list(range(1000000))
list2 = list(range(1000000))

# Using Python Lists
start = time.time()

dot_product = sum(list1[i] * list2[i] for i in range(len(list1)))

end = time.time()

print("Dot product using Python lists:", dot_product)
print("Time taken using Python lists:", end - start)


# Using NumPy Arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

dot_product_np = np.dot(arr1, arr2)

end = time.time()

print("\nDot product using NumPy:", dot_product_np)
print("Time taken using NumPy arrays:", end - start)

Dot product using Python lists: 333332833333500000
Time taken using Python lists: 0.06361651420593262

Dot product using NumPy: 333332833333500000
Time taken using NumPy arrays: 0.0017044544219970703


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [9]:
import numpy as np
import time
import random

# Matrix size
n = 1000

# Using Python Lists
A = [[random.random() for _ in range(n)] for _ in range(n)]
B = [[random.random() for _ in range(n)] for _ in range(n)]

start = time.time()

# Initialize result matrix
result = [[0 for _ in range(n)] for _ in range(n)]

# Matrix multiplication
for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Time taken using Python lists:", end - start)

# Using NumPy Arrays
A_np = np.random.random((n, n))
B_np = np.random.random((n, n))

start = time.time()

result_np = np.dot(A_np, B_np)

end = time.time()

print("Time taken using NumPy arrays:", end - start)

Time taken using Python lists: 231.77931928634644
Time taken using NumPy arrays: 0.046905517578125
